# fly.toml app configuration file generated for part1-ancient-wind-9065 on 2024-08-02T15:35:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part1-ancient-wind-9065'
primary_region = 'ams'

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
